### ISSUE TITLE
CLAP and VST3 and built but not installed

### ISSUE THREAD

**Issue by ycollet** [zamaudio/zam-plugins#92]
CLAP and VST3 versions of zam plugins and built but not installed.

**Comment by zamaudio** [comment]
I don't care too much about installing vst3 or clap.  I prefer lv2 format as it is a free plugin format developed by the community.  I will accept pull request if you want to figure out where to put them on a GNU/Linux system, otherwise the macOS installer probably already puts them somewhere on mac.  Windows, well who cares about that, you're on your own with those.

**Comment by ycollet** [comment]
Up to now I managed the install manually by copying the files in bin.
Maybe you can add a line about that in the README file ?
I close the ticket.
